create table agenda(
    id_agenda bigint not null generated by default as identity primary key,
    data_criacao timestamp,
    data_hora_inicio timestamp,
    data_hora_fim timestamp,
    tipo_atividade varchar(255),
    status_conclusao varchar(255),
    porcntagem_conclusao decimal
);